INSERT INTO portfolio (title, category, image_url, description, is_active) VALUES 
('001 Sepatu Pria', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/strica-BG.png', 'Template de P??gina de Vendas Elementor', true),
('09 Camera', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-BG-010.png', 'Template de P??gina de Vendas Elementor', true),
('98 Thankyou5', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Section-099-ThankYou-BG-Img-Ornament.png', 'Template de P??gina de Vendas Elementor', true),
('99 Thankyou6', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Section-100-ThankYou-BG-Img-Ornament-1.png', 'Template de P??gina de Vendas Elementor', true),
('100 Workshop', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-101-BG-Img-Ornament.png', 'Template de P??gina de Vendas Elementor', true),
('106 EO Wedding2', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-017-BG-Img-.png', 'Template de P??gina de Vendas Elementor', true),
('107 Reseller Maknan', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-108-BG-Img-Ornament.png', 'Template de P??gina de Vendas Elementor', true),
('11 Kesehatan', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-BG.png', 'Template de P??gina de Vendas Elementor', true),
('108 Sepatu Pria', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-109-BG-Ornament.png', 'Template de P??gina de Vendas Elementor', true),
('109 baju Muslim Pria', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-110-BG-Ornament.png', 'Template de P??gina de Vendas Elementor', true),
('12 ECourse', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/logo.png', 'Template de P??gina de Vendas Elementor', true),
('14 Mobil', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-BG-014.png', 'Template de P??gina de Vendas Elementor', true),
('15 Mainan', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-BG-Component-015.png', 'Template de P??gina de Vendas Elementor', true),
('16 Jasa Sosmed', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-BG-Gradient-1.png', 'Template de P??gina de Vendas Elementor', true),
('17 Bike', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/ornament.png', 'Template de P??gina de Vendas Elementor', true),
('18 Jasa Hosting', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/bghero.png', 'Template de P??gina de Vendas Elementor', true),
('002 Alat Pancing', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-002-BG-Img-Component.png', 'Template de P??gina de Vendas Elementor', true),
('20 Pendidikan', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-020-BG-Component.png', 'Template de P??gina de Vendas Elementor', true),
('21 Creative Agency', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Y.STUDIO.png', 'Template de P??gina de Vendas Elementor', true),
('23 Souvenir', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-023-BG-Img-1.png', 'Template de P??gina de Vendas Elementor', true),
('25 Fashion Muslim', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-BG-Komponen.png', 'Template de P??gina de Vendas Elementor', true),
('26 Motorcycle', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-026-BG-Overlay.png', 'Template de P??gina de Vendas Elementor', true),
('27 Jam Tangan', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-027-Img-right.png', 'Template de P??gina de Vendas Elementor', true),
('29 Tas', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-028-BG-Img.png', 'Template de P??gina de Vendas Elementor', true),
('28 Diet', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-Dietly-029-Img-BG.png', 'Template de P??gina de Vendas Elementor', true),
('03 Ebook', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/bg-pattern-2.png', 'Template de P??gina de Vendas Elementor', true),
('04 Fashion Anak', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/image-7.png', 'Template de P??gina de Vendas Elementor', true),
('06 Fashion Wanita', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/image-8.png', 'Template de P??gina de Vendas Elementor', true),
('07 Interior', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Interior-Header-Left-BG-1.png', 'Template de P??gina de Vendas Elementor', true),
('08 makeup', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Group-3-1.png', 'Template de P??gina de Vendas Elementor', true),
('79 Fashion Wanita2', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-079-BG-Component.png', 'Template de P??gina de Vendas Elementor', true),
('84 Fashion Anak2', 'Modelos de P??gina', 'https://landingkit.imers.gq/wp-content/uploads/2019/12/Header-084-BG-Img.png', 'Template de P??gina de Vendas Elementor', true);

